name: hello-world-actions

on: 
 push:
   branches:
     - "lab"
     - "staging"
     - "production"
 pull_request:
   branches:
     - "lab"
     - "staging"
     - "production"

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  GITHUB_BASE_BRANCH: ${{ github.base_ref }}
  
jobs: 
   notify-local-machine-jenkins-run:
     runs-on: [self-hosted, macOS, X64]
     steps:
      - run: >-
            curl \
              -X GET \
              http://localhost:4444/job/test-custom-jenkins/buildWithParameters?token=TOKEN&buildBranch=${GITHUB_BASE_BRANCH}&buildEvent=${GITHUB_EVENT_NAME}&prNumber=${GITHUB_PR_NUMBER}
