name: hello-world-actions

on: 
 push:
   branches:
     - "lab"
     - "staging"
     - "production"
 pull_request:
   branches:
     - "lab"
     - "staging"
     - "production"

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_EVENT_NAME: ${{github.event_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  
jobs: 
   set-env:
     runs-on: [self-hosted, macOS, X64]
     steps:
      - run: |
         if [[ $GITHUB_EVENT_NAME = "push" ]]; then
            $COMMIT_SHA=$(echo $GITHUB_SHA)
         else
            $COMMIT_SHA=$(echo $GITHUB_HEAD_SHA)
         fi
         echo $COMMIT_SHA
